[build]
  publish = "."
  command = "echo 'No build required'"

# Enable Netlify Identity + Git Gateway
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin"
  to = "/static/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/static/admin/:splat"
  status = 200

# Required for Git Gateway
[[headers]]
  for = "/.netlify/git-gateway/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"