[build]
  publish = "."
  command = "echo 'Build complete'"

[[redirects]]
  from = "/admin"
  to = "/static/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/static/admin/:splat"
  status = 200
